export * from './Realm.datadragon.dto'
export * from './Champions.datadragon.dto'
export * from './Queues.datadragon.dto'
export * from './Maps.datadragon.dto'
export * from './GameModes.datadragon.dto'
