/**
 * Tiers
 */
export enum Levels {
  NONE = 'NONE',
  IRON = 'IRON',
  BRONZE = 'BRONZE',
  SILVER = 'SILVER',
  GOLD = 'GOLD',
  PLATINUM = 'PLATINUM',
  DIAMOND = 'DIAMOND',
  MASTER = 'MASTER',
  GRANDMASTER = 'GRANDMASTER',
  CHALLENGER = 'CHALLENGER',
  HIGHEST_NOT_LEADERBOARD_ONLY = 'HIGHEST_NOT_LEADERBOARD_ONLY',
  HIGHEST = 'HIGHEST',
  LOWEST = 'LOWEST'
}
