/**
 * Tiers
 */
export const enum Tiers {
  CHALLENGER = 'CHALLENGER',
  GRANDMASTER = 'GRANDMASTER',
  MASTER = 'MASTER',
  DIAMOND = 'DIAMOND',
  PLATINUM = 'PLATINUM',
  GOLD = 'GOLD',
  SILVER = 'SILVER',
  BRONZE = 'BRONZE',
  IRON = 'IRON'
}
