name: Deploy
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - run: yarn install --frozen-lockfile

      - run: npm publish --provenance --access public --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ""
          NPM_TOKEN: ""
