name: Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        # No scope for unscoped package; do not set scope here
    - run: yarn
    - run: yarn publish --registry https://registry.npmjs.org
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        npm_config_registry: https://registry.npmjs.org
